Directory: C:\Users\hp\imambasha-devops-proof\ci-cd\jenkins

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----              [date/time]           [size] Jenkinsfile
