name: Node.js Deployment Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Deploy to AWS EC2
        run: |
          ssh -i ${{ secrets.SSH_KEY }} ec2-user@your-ec2-ip "
          cd /var/www/my-app && git pull origin main && pm2 restart all"
